# EmergentMUD - A modern MUD with a procedurally generated world.
# Copyright (C) 2016 BoneVM, LLC
#
# This file is part of EmergentMUD.
#
# EmergentMUD is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EmergentMUD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

spring:
  application:
    name: core
  resources:
    chain:
      enabled: true

facebook:
  client:
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

google:
  client:
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    authenticationScheme: query
    scope: profile
    pre-established-redirect-uri: http://www.emergentmud.com:8080/login/google
    registered-redirect-uri: http://www.emergentmud.com:8080/login/google
    use-current-uri: false
  resource:
    userInfoUri: https://www.googleapis.com/plus/v1/people/me